name: {{name.snakeCase()}}
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_route: ^9.2.0 
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_flavor: ^3.1.3
  flutter_pretty_dio_logger: ^3.0.0
  fpdart: ^1.1.0
  google_fonts: ^6.2.1
  internet_connection_checker_plus: ^2.5.1
  shared_preferences: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
